### ISSUE TITLE
Welcome to space-war Discussions!

### ISSUE THREAD

**Issue by Mk-Mkrtich** [mkrtich204655/space-war#2]
### Discussed in https://github.com/mkrtich204655/space-war/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **mkrtich204655** May  7, 2024</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by TaronVardanyan** [comment]
is this an issue?
